name: Build VS Code Extension

on:
  push:
    tags:
      - v*
    types: [created]
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build extension
      run: npm run compile
      
    - name: Package extension
      run: npm install -g @vscode/vsce && vsce package
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix-package
        path: "*.vsix" 